include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

image: node:16

stages:
- setup
- test
- build
- publish

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

.node-cache:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - node_modules/

setup-js:
  stage: setup
  extends: .node-cache
  script:
  - npm install

test-js:
  stage: test
  extends: .node-cache
  script:
  - npm run test

lint-js:
  stage: test
  extends: .node-cache
  script:
  - npm run lint

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - .sonar/cache
  script:
  - sonar-scanner

build-js:
  stage: build
  extends: .node-cache
  script:
  - npm run build
  artifacts:
    paths:
    - www
    expire_in: 1 days

pages:
  stage: publish
  script:
  - mv www public
  dependencies:
  - build-js
  artifacts:
    paths:
    - public
  rules:
  -  if: $CI_COMMIT_BRANCH == "master"
