include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

image: node:12

stages:
- setup
- test
- build
- publish

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

setup-js:
  stage: setup
  script:
  - npm install

test-js:
  stage: test
  script:
  - npm run test

lint-js:
  stage: test
  script:
  - npm run lint

build-js:
  stage: build
  script:
  - npm run build
  artifacts:
    paths:
    - dist
    expire_in: 1 days

pages:
  stage: publish
  script:
  - mv dist public
  dependencies:
  - build-js
  artifacts:
    paths:
    - public
  rules:
  -  if: $CI_COMMIT_BRANCH == "master"