const options = {
  fillerLetters: 'abcdefghijklmnopqrstuvwxyz',
  allWords: [
    'gate',
    'message',
    'courage',
    'desk',
    'lamp',
    'vehicle',
    'lemonade',
    'speaker',
    'bread',
    'guitar',
    'machine',
    'computer',
    'car',
    'age',
    'skill',
    'camera',
    'basket',
    'city',
    'person',
    'student',
    'imagination',
    'football',
  ],
  boardSize: { width: 20, height: 20 },
  shuffle: true,
  expectedScore: 0.8,
};

export default options;
